### ISSUE TITLE
[opentelemetry] add node/systemd journal logs for OpenTelemetry

### ISSUE THREAD

**Issue by timojohlo** [cloudoperators/greenhouse-extensions#243]
## Context 
We also want to collect system logs from the underlying node. This is done by implementing a journal log receiver as part of collector. All logs from OS managed by systemd are binary, so they can only be read by journalctl.  

## Acceptance Criteria 
- [x] implement journal receiver together with linux OS command journal ctl to read binary format

## References
[#148 ](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/journaldreceiver)

**Comment by Kuckkuck** [comment]
We need an own image, because the node systemd journal logs are binary encoded and the otel plugin only works in combination with the linux os journalctl command. [journal format](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/stanza/docs/operators/journald_input.md?plain=1).

We also need a repository or location for the Dockerfile, a build pipeline and a docker hub, where the image can be published.

**Comment by timojohlo** [comment]
Is working with the latest PR #242 but will need testing to check the functionality of the os journalctl command
