### ISSUE TITLE
[opentelemetry] Build Monitoring for OpenTelemetry

### ISSUE THREAD

**Issue by timojohlo** [cloudoperators/greenhouse-extensions#339]
## Context 
We need to observe the behavior of OpenTelemetry itself and eventually determine faulty at quality, infrastructure, processing or computation. For this we need a to expose own metrics to Prometheus and build dashboard that allows to observe such behavior.

## Acceptance Criteria 
- [x] expose OTel metrics to prometheus in internal cluster
- [x] build Plutono dashboard to observe stability for OpenTelemetry

**Comment by Kuckkuck** [comment]
The otel-logs collector is exposing internal metrics about the logs collection by default without any useful labels. That's why we scrape these metrics with the otel logs collector itself, add in a second step labels like region,  cluster and nodename and removing unused labels. These enriched metrics are exposed again on a different port. Prometheus is picking them up via podmonitor.

**Comment by artherd42** [comment]
https://github.com/monitoringartist/opentelemetry-collector-monitoring could be a starting point for dashboard and alerts for the OTEL collector.

**Comment by Kuckkuck** [comment]
Enhance monitoring #409 follow up ticket
